### PR TITLE
Titanium 6+

### PR DESCRIPTION
**Pull request by m1ga**
Update manifest and binary

### CODE REVIEW

**Comment by hansemannn** [comment]
Did the same [here](https://github.com/mpociot/TiAndroidAutofocus/compare/master...hansemannn:master?expand=1), so the PR afterwards. Guess your's is enough here.

**Comment by guiled** [comment]
👍

**Comment by hansemannn** [comment]
@mpociot ping :-)

**Comment by mpociot** [comment]
Sorry, merged it - thanks!

**Pull request merged**
